Major enhancement to "make tests". All but Python tests cleaned up to
* Makefile.am, tests/Makefile.am, tests/REC/Makefile.am,
  tests/REC1/Makefile.am, tests/REC2/Makefile.am,
  tests/XSLTMark/Makefile.am, tests/docbook/Makefile.am,
  tests/exslt/common/Makefile.am, tests/exslt/date/Makefile.am,
  tests/exslt/functions/Makefile.am, tests/exslt/math/Makefile.am,
  tests/exslt/sets/Makefile.am, tests/exslt/strings/Makefile.am,
  tests/extensions/Makefile.am, tests/general/Makefile.am,
  tests/keys/Makefile.am, tests/multiple/Makefile.am,
  tests/namespaces/Makefile.am, tests/numbers/Makefile.am,
  tests/reports/Makefile.am, test/xmlspec/Makefile.am,
  tests/general/bug-60.err, tests/docbook/result/html/gdp-handbook.err,
  tests/REC/test-2.5-1.err:
  Major enhancement to "make tests". All but Python tests
  cleaned up to produce minimum summary output if no problems.
* tests/general/bug-145.xsl, tests/general/bug-145.err,
  tests/docs/Makefile.am, tests/docs/bug-145.xml:
  Added test case for bugzilla bug 135938

diff --git a/tests/REC/Makefile.am b/tests/REC/Makefile.am
--- a/tests/REC/Makefile.am
+++ b/tests/REC/Makefile.am
@@ -19,7 +19,7 @@ EXTRA_DIST = 						\
     test-16.1-2.out test-16.1-2.xml test-16.1-2.xsl	\
     test-2.3-1.out test-2.3-1.xml test-2.3-1.xsl	\
     test-2.3-2.out test-2.3-2.xml test-2.3-2.xsl	\
-    test-2.5-1.out test-2.5-1.xml test-2.5-1.xsl	\
+    test-2.5-1.out test-2.5-1.xml test-2.5-1.xsl test-2.5-1.err	\
     test-2.6.2-1.out test-2.6.2-1.xml test-2.6.2-1.xsl	\
     test-5.2-1.out test-5.2-1.xml test-5.2-1.xsl	\
     test-5.2-2.out test-5.2-2.xml test-5.2-2.xsl	\
@@ -80,25 +80,66 @@ valgrind:
 
 test tests: $(top_builddir)/xsltproc/xsltproc
 	@(echo > .memdump)
-	@(for i in $(srcdir)/*.xsl ; do \
+	@echo '## Running REC tests'
+	-@(for i in $(srcdir)/*.xsl ; do \
 	  name=`basename $$i .xsl` ; \
-	  if [ ! -f $(srcdir)/$$name.xml ] ; then continue ; fi ; \
-	  echo $$name.xml ; \
-	  $(CHECKER) $(top_builddir)/xsltproc/xsltproc $(srcdir)/$$name.xsl $(srcdir)/$$name.xml > $$name.res;\
-	  if [ ! -f $(srcdir)/$$name.out ] ; then cp $$name.res $(srcdir)/$$name.out ; \
-	  else if  [ ! -s $$name.res ] ; then echo "Fatal error, no $$name.res\n" ; \
-	  else diff $(srcdir)/$$name.out $$name.res ; fi ; fi; \
-	  grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0" || true;\
-	  rm -f $$name.res ; \
+	  if [ ! -f $(srcdir)/$$name.xml ] ; then \
+	  	continue ; \
+	  fi ; \
+	  log=`$(CHECKER) $(top_builddir)/xsltproc/xsltproc \
+	  	$(srcdir)/$$name.xsl $(srcdir)/$$name.xml \
+	  	> $$name.res 2>$$name.bad ; \
+	  if [ ! -f $(srcdir)/$$name.out ] ; then \
+	  	cp $$name.res $(srcdir)/$$name.out ; \
+		if [ -s $$name.bad ] ; then \
+			cp $$name.bad $(srcdir)/$$name.err ; \
+		fi ; \
+	  else \
+	  	if  [ ! -s $$name.res ] ; then \
+	  		echo "Fatal error, no $$name.res\n" ; \
+	  	else \
+	  		diff $(srcdir)/$$name.out $$name.res ; \
+			if [ -s $$name.err ] ; then \
+				diff $(srcdir)/$$name.err $$name.bad ; \
+			else \
+				diff /dev/null $$name.bad ; \
+			fi ; \
+	  	fi ; \
+	  fi ; \
+	  grep "MORY ALLO" .memdump  | \
+	  grep -v "MEMORY ALLOCATED : 0" || true` ; \
+	  if [ -n "$$log" ] ; then \
+	  	echo $$name result ; \
+		echo $$log ; \
+	  fi ; \
+	  rm -f $$name.res $$name.bad ; \
 	  done)
 	@(for i in $(srcdir)/stand*.xml ; do \
 	  name=`basename $$i .xml` ; \
-	  echo $$name.xml ; \
-	  $(CHECKER) $(top_builddir)/xsltproc/xsltproc $(srcdir)/$$name.xml > $$name.res;\
-	  if [ ! -f $(srcdir)/$$name.stand.out ] ; then cp $$name.res $(srcdir)/$$name.stand.out ; \
-	  else if  [ ! -s $$name.res ] ; then echo "Fatal error, no $$name.res\n" ; \
-	  else diff $(srcdir)/$$name.stand.out $$name.res ; fi ; fi; \
-	  grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0" || true;\
-	  rm -f $$name.res ; \
+	  log=`$(CHECKER) $(top_builddir)/xsltproc/xsltproc \
+	  	$(srcdir)/$$name.xml > $$name.res 2>$$name.bad ;\
+	  if [ ! -f $(srcdir)/$$name.stand.out ] ; then \
+		cp $$name.res $(srcdir)/$$name.stand.out ; \
+		if [ -s $$name.bad ] ; then \
+			cp $$name.bad $(srcdir)/$$name.stand.err ; \
+		fi ; \
+	  else \
+	  	if  [ ! -s $$name.res ] ; then \
+	  		echo "Fatal error, no $$name.res\n" ; \
+	  	else \
+	  		diff $(srcdir)/$$name.stand.out $$name.res ; \
+			if [ -s $$name.stand.err ] ; then \
+	  			diff $(srcdir)/$$name.stand.err $$name.bad ; \
+			else \
+				diff /dev/null $$name.bad; \
+			fi ; \
+		fi ; \
+	  fi ; \
+	  grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0" || true` ; \
+	  if [ -n "$$log" ] ; then \
+	  	echo $$name result ; \
+		echo $$log ; \
+	  fi ; \
+	  rm -f $$name.res $$name.bad ; \
 	  done)
 
