added Embedding Stylesheets added the test from the REC about it tried to
* FEATURES libxslt/xsltproc.c libxslt/transform.c
  libxslt/xsltInternals.h: added Embedding Stylesheets
* tests/REC/Makefile.am tests/REC/stand-2.7-1.*: added the test
  from the REC about it
* libxslt/transform.c libxslt/extra.[ch] libxslt/preproc.c:
  tried to accomodate the various (and changing) proprietary
  ways of implementing chunking.
* tests/docbook/result/xtchunk/html: now output is generated in
  ISO-8859-1
Daniel

diff --git a/tests/REC/Makefile.am b/tests/REC/Makefile.am
--- a/tests/REC/Makefile.am
+++ b/tests/REC/Makefile.am
@@ -84,4 +84,14 @@ test tests: $(top_builddir)/libxslt/xsltproc
 	  grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0" || true;\
 	  rm -f $$name.res ; \
 	  done)
+	@(for i in $(srcdir)/stand*.xml ; do \
+	  name=`basename $$i .xml` ; \
+	  echo $$name.xml ; \
+	  $(top_builddir)/libxslt/xsltproc $(srcdir)/$$name.xml > $$name.res;\
+	  if [ ! -f $(srcdir)/$$name.stand.out ] ; then cp $$name.res $(srcdir)/$$name.stand.out ; \
+	  else if  [ ! -s $$name.res ] ; then echo "Fatal error, no $$name.res\n" ; \
+	  else diff $(srcdir)/$$name.stand.out $$name.res ; fi ; fi; \
+	  grep "MORY ALLO" .memdump  | grep -v "MEMORY ALLOCATED : 0" || true;\
+	  rm -f $$name.res ; \
+	  done)
 
